// Todo constants
module.exports = {
  NEW_ITEM: 'NEW_ITEM',
  SAVE_ITEM: 'SAVE_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  GET_TEQUILA: 'GET_TEQUILA',
  GET_TEQUILA_RESPONSE: 'GET_TEQUILA_RESPONSE',
  GET_FABRICANTE: 'GET_FABRICANTE',
  GET_FABRICANTE_RESPONSE: 'GET_FABRICANTE_RESPONSE',
};
